#!/usr/bin/env bash
#script that will display information about subdomains

myRecords ()
{
  dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F " " 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }' 
}
if [ "$#" -eq 2 ]
then
 myRecords "$2.$1" "$2"
else
    myRecords "www.$1" "www"
    myRecords "lb-01.$1" "lb-01"
    myRecords "web-01.$1" "web-01"
    myRecords "web-02.$1" "web-02"
fi
